name: bluetooth_radar_demo
description: "Demo App Bluetooth Radar"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.35.2
  workmanager: ^0.5.2
  flutter_local_notifications: ^18.0.1

  flutter_logs: ^2.0.0
  rxdart: ^0.28.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
